### ISSUE TITLE
How its works?

### ISSUE THREAD

**Issue by x1pepe** [EgonOlsen71/petsciiator#4]
Hi! and sorry for my rude question but I couldn't make it works, I am in Linux, I put a alien.jpg in the /dist folder.
If I type:
java -jar petsciiator.jar alien.jpg   ... I get:
"There is not attribute i petsciiator.jar"
Please, can you type a complete line to convert alien.jpg and use the final result on a BBS?
Thanks in advance.

**Comment by EgonOlsen71** [comment]
Sorry for the late reply, I haven't seen this. Anyway...there is no manifest in the jar specifying the main class, which is why it doesn't work with -jar.

You can use the petsii.sh script instead. Like so:

`./petscii.sh /format=bbs alien.jpg`

You might have to set file permissions before being able to run the script though. Or just look at the script and do something similar yourself.
